# Generated by Django 3.0.4 on 2020-05-16 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('url', models.URLField()),
                ('source_name', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='customer_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fname', models.CharField(max_length=50)),
                ('customer_lname', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='customer_bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cb_bookmark_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cb_bookmark_ids', to='CB_app.bookmark')),
                ('cb_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cb_customer_ids', to='CB_app.customer_profile')),
            ],
        ),
        migrations.AddField(
            model_name='bookmark',
            name='bookmarks',
            field=models.ManyToManyField(through='CB_app.customer_bookmark', to='CB_app.customer_profile'),
        ),
    ]
